### ISSUE TITLE
Tutorials Roadmap

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/TuringTutorials#1]
My understanding of this repo is that it is to be the home for all of Turing's educational materials. I've reviewed a lot of the existing stuff we have in TuringDemos and TuringExamples, but so far there's not a lot outside of brief code blurbs and a couple of Jupyter notebooks without a lot of commentary.

@trappmartin noted that [Edward's tutorials](http://edwardlib.org/tutorials/) are something of a target for us. I can see why, they are exceptionally thorough and very pleasant to read with a conversational approach. They also tend assume limited familiarity with probabilistic methods, which I think of as a plus.

So, here are my guidelines for what I think would make a good set of tutorials.

1. Highlight the ease of use of Turing. Easy to read, easy to write, easy to understand.
2. Usable by reasonably informed layman. Someone with a basic to intermediate understanding of statistics should be able to understand most of the tutorial and expand it to their problem. This doesn't necessarily mean that we want to dumb everything down -- I still think there's room to showcase some really complex and nifty stuff, but we should try and make everything as accessible as is reasonable.
3. Solve an example problem with real data. This might be any of the data sets in [RDatasets](https://github.com/johnmyleswhite/RDatasets.jl) or [MLDatasets](https://github.com/JuliaML/MLDatasets.jl). In cases where a real-world data set might not be available or isn't applicable (are there any of those in this field? I have no idea) we should make sure that synthetic data is described (table headers, a chart or two, etc) so people can easily see what it looks like.
4. Consistent in tone, information content, and pedagogical approach.

I'll be adding issues for each tutorial type we should eventually have, along with what we have in place elsewhere to see if we can adapt some of the models already written. More to come on that, but figured I should get out what kinds of things I think are valuable in a tutorial.

**Comment by trappmartin** [comment]
Regarding 3., I think it should be possible to find a dataset in the mentioned pkgs or via other sources for every show-case application. Synthetic data, however, might sometimes simplify the documentation, e.g. for a GMM example.

**Comment by mkborregaard** [comment]
Hey, I just found this repo. The first notebook "introduction" and the planned expansions look really sweet. Looking forward to following this!

**Comment by cpfiffer** [comment]
@mkborregaard Happy we could showcase some of our cool stuff. Let us know if there's anything specific you think might be interesting to include in the tutorials.

**Comment by mkborregaard** [comment]
I will! By the way, StatPlots is better at plotting distributions than just Plots - if you use StatPlots you can replace the line 
```julia
   plot(x, pdf.(Ref(updated_belief), x), 
```
with
```julia
   plot(updated_belief, x,
```

**Comment by mkborregaard** [comment]
In fact you shouldn't need the `x` at all, `plot(updated_belief,` should be sufficient. I could make a PR, but a little uncertain how to do that on a Jupyter notebook, where so much of the file content is auto-generatd.

**Comment by cpfiffer** [comment]
Typically we'd make the change and then just rerun all the cells before committing the file, if you'd like to do so. Otherwise I can probably get to it this evening when I'm back at my machine.

**Comment by mkborregaard** [comment]
I don't mind but I'm working on a plotting pr on mcmcchains first

**Comment by cpfiffer** [comment]
@mkborregaard The introduction notebook has been updated to use StatPlots and also handles the changes to MCMCChain's syntax.
