### ISSUE TITLE
Logistic Regression 

### ISSUE THREAD

**Issue by yebai** [TuringLang/TuringTutorials#10]
Bayesian logistic regression is a useful model used in many applications. We might want to consider adding the example from 

https://github.com/TuringLang/Turing.jl/issues/546

to tutorials.

**Comment by trappmartin** [comment]
I agree, this was already proposed in issue #3 and I think @cpfiffer is working on it.

**Comment by cpfiffer** [comment]
That's correct, I'm still doing the write-up for this one. It should hopefully be along shortly.

**Comment by cpfiffer** [comment]
Merged over with #17. Does anyone have any comments on it before I close this issue?

**Comment by trappmartin** [comment]
I'm happy, the tutorial in #17 is really nice.
