### ISSUE TITLE
CompatHelper opens dozens of pull requests

### ISSUE THREAD

**Issue by rikhuijzer** [TuringLang/TuringTutorials#215]
Currently, the tutorials all have their own environment. This causes CompatHelper to open dozens of pull requests when multiple dependencies should be updated. Even when these are resolved, one new package version may introduce 10 new pull requests (one per tutorial).

I would suggest moving to one global environment to avoid spamming the 10 people who watch this repository, but I also understand that there are drawbacks to having one environment.

@devmotion, @torfjelde, @cpfiffer, any thoughts?

EDIT: Apologies for the mess this has caused, by the way. I could have predicted that we would end up with 87 PRs.

**Comment by torfjelde** [comment]
If that's the alternative, then IMO we should instead just _not_ use CompatHelper here. Global env is unfortuante because eventually we'll have _a lot_ of deps for all tutorials leading to unnecessary bloat, increased compile-times, etc. IMO we want the tutorials to be something people can actually open up and play around with; a global env IMO goes against that.

**Comment by rikhuijzer** [comment]
> Global env is unfortuante because eventually we'll have a lot of deps for all tutorials leading to unnecessary bloat, increased compile-times, etc.

Okay, very good point.

> what do they do over at SciML?

There, they get multiple PRs and merge those. For example:

- https://github.com/SciML/SciMLTutorials.jl/pull/372
- https://github.com/SciML/SciMLTutorials.jl/pull/373
- https://github.com/SciML/SciMLTutorials.jl/pull/374
- https://github.com/SciML/SciMLTutorials.jl/pull/375
- https://github.com/SciML/SciMLTutorials.jl/pull/392
- https://github.com/SciML/SciMLTutorials.jl/pull/393
- https://github.com/SciML/SciMLTutorials.jl/pull/394
- https://github.com/SciML/SciMLTutorials.jl/pull/395
- https://github.com/SciML/SciMLTutorials.jl/pull/396

**Comment by devmotion** [comment]
> Global env is unfortuante because eventually we'll have _a lot_ of deps for all tutorials leading to unnecessary bloat, increased compile-times, etc. IMO we want the tutorials to be something people can actually open up and play around with; a global env IMO goes against that.

I agree, IMO we should really not use a global environment. It leads to a lot of unnecessary dependencies for individual tutorials, makes it more difficult to update the tutorials, and increases the probability of package conflicts. If the packages are somewhat mature, hopefully breaking updates don't occur too often and we just have to cope with the PRs (if we do not rebuild all tutorials it will also not put too much stress on GH actions).

**Comment by rikhuijzer** [comment]
Okay. I’m convinced. Thank you both!
