### ISSUE TITLE
The "Bayesian Differential Equation" tutorial needs small improvements

### ISSUE THREAD

**Issue by nathanaelbosch** [TuringLang/TuringTutorials#292]
From: https://github.com/TuringLang/Turing.jl/edit/master/docs/_tutorials/10_BayesianDiffEq.md

The tutorial results seem to have changed since its initial writing. For example, the plot in the __Data retrodiction__ section does not reproduce the true ODE solution "quite accurately", since there is a big mismatch between the parameters in the three chains. I suspect that to resolve this issue and fix the example, some minor parameter tweaking could already be sufficient.

**Comment by devmotion** [comment]
The tutorial was just updated yesterday (#296) and runs fine with the latest versions of Turing and DifferentialEquations (see https://turing.ml/dev/tutorials/10-bayesian-differential-equations/). It's part of our CI pipeline, and hence it should be easy to spot and fix regressions when e.g. updating Turing or DifferentialEquations in the future.
