### ISSUE TITLE
Linear Regression

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/TuringTutorials#3]
Should we make a tutorial on linear regression? I am slightly on the fence on this one. I think it would be useful to have a brief example on how to do Bayesian linear regression, because pretty much anyone with any stats training knows how to do a regression of this sort from a frequentist perspective -- it might help build the groundwork for people on how to think about specifying their models.

Thoughts?

**Comment by trappmartin** [comment]
I think we should have an example on *logistic regression* and one on *linear regression*. Maybe both in the same notebook? People already asked for a tutorial on *logistic regression* and I think it is a nice and simple show-case because of the points you raised.

see: https://github.com/TuringLang/TuringExamples/blob/master/nuts-paper/lr_nuts.jl

**Comment by cpfiffer** [comment]
Great idea! I wrote a linear regression model last night and I'll integrate the LR model into it.

**Comment by goedman** [comment]
Is this simple linear model published? I'm trying:

```
using Turing, MCMCChain, Flux.Tracker

data = (y = [1.0, 3.0, 3.0, 3.0, 5.0], x = [1.0, 2.0, 3.0, 4.0, 5.0])

@model line(y, x) = begin
    #priors
    alpha ~ Normal(0.0, 10.0)
    beta ~ Normal(0.0, 10.0)
    s ~ InverseGamma(0.001, 0.001)
    #model
    mu = alpha .+ beta*x
    for i in 1:length(y)
      y[i] ~ Normal(mu[i], s)
    end
end
  
chn = sample(line(data.y, data.x), HMC(1000, 0.5, 10))
```

and get many warnings like:

```
┌ Warning: Numerical error has been found in gradients.
└ @ Turing ~/.julia/dev/Turing/src/core/ad.jl:114
┌ Warning: grad = [0.30767, 1.0688, NaN]
└ @ Turing ~/.julia/dev/Turing/src/core/ad.jl:115
```

The estimates don't make sense. Is this maybe also an AD issue or, more likely, is my model wrong?

**Comment by cpfiffer** [comment]
@goedman The [logistic model](https://github.com/TuringLang/TuringTutorials/blob/master/2_LogisticRegression.ipynb) is fairly similar, if you'd like to take a look at that while the linear regression example is built. 

As to your model, it looks like you just needed to adjust the `epsilon` parameter in `HMC` to a smaller number. Try going from `chn = sample(line(data.y, data.x), HMC(1000, 0.5, 10))` to `chn = sample(line(data.y, data.x), HMC(1000, 0.01, 10))`.

Here's your whole model again with a slightly changed `HMC` call:

```julia
using Turing, MCMCChain, Flux.Tracker

data = (y = [1.0, 3.0, 3.0, 3.0, 5.0], x = [1.0, 2.0, 3.0, 4.0, 5.0])

@model line(y, x) = begin
    #priors
    alpha ~ Normal(0.0, 10.0)
    beta ~ Normal(0.0, 10.0)
    s ~ InverseGamma(0.001, 0.001)
    #model

    mu = alpha .+ beta*x
    for i in 1:length(y)
      y[i] ~ Normal(mu[i], s)
    end
end
  
chn = sample(line(data.y, data.x), HMC(1000, 0.01, 10))
```
Let me know if that works for you!

**Comment by goedman** [comment]
Thank you @cpfiffer That works great!

**Comment by yebai** [comment]
Closed by https://github.com/TuringLang/TuringTutorials/pull/19
