### ISSUE TITLE
Contribute translation of PymC prophet like model

### ISSUE THREAD

**Issue by SebastianCallh** [TuringLang/TuringTutorials#306]
Hi! I [rewrote](https://github.com/SebastianCallh/turing-air-passengers) the [Pymc Air passengers - Prophet-like model](https://docs.pymc.io/en/v3/pymc-examples/examples/time_series/Air_passengers-Prophet_with_Bayesian_workflow.html) in Julia. It is a simpler model than what's discussed in related issues #80 and #28 but if you like I can write up a notebook and contribute it to this repo.

**Comment by yebai** [comment]
thanks, @SebastianCallh - it looks like an interesting tutorial to have!
