### ISSUE TITLE
Add link to Statistical Rethinking models?

### ISSUE THREAD

**Issue by jlewis91** [TuringLang/TuringTutorials#37]
I've found the models implemented as part of the StatisticalRethinking.jl repo to be quite helpful, it might be worthwhile to add a link to them in the readme to this repo (at least until more examples are available here).

https://github.com/StatisticalRethinkingJulia/TuringModels.jl

**Comment by cpfiffer** [comment]
Great idea! I'll add it. Thank you for reminding us to do this seemingly-obvious thing that I have missed.

**Comment by cpfiffer** [comment]
Updated on the README. Thanks again!

**Comment by jlewis91** [comment]
Thank you!
