### ISSUE TITLE
Link in Repo's 'About' points to turing.ml and not turinglang.org

### ISSUE THREAD

**Issue by patrickm663** [TuringLang/TuringTutorials#392]
Hi

A small thing I picked up is that the link in the 'About' section of the Repo is directing users to https://turing.ml/dev/tutorials/ rather than https://turinglang.org/dev/tutorials/.

Thanks.

Kind regards
Patrick

**Comment by devmotion** [comment]
Thank you! I fixed it a few days ago I think, without knowing about this issue :sweat_smile:
