### ISSUE TITLE
02 Bayesian Logistic Regression points to main page

### ISSUE THREAD

**Issue by mistermichaelll** [TuringLang/TuringTutorials#431]
I noticed that in the `Turing.jl` [docs](https://turing.ml/v0.22/tutorials/),`Bayesian Logistic Regression` points to this link: https://turing.ml/v0.22/tutorials/02-logistic-regression.
<img width="212" alt="Screenshot 2023-11-24 at 4 08 51 PM" src="https://github.com/TuringLang/Turing.jl/assets/33233019/2e711b23-1714-4487-8555-131094ea7849">

However, clicking this link (even outside of the docs) brings you back to the main page of the documentation rather than to this tutorial. 

I believe the issue may be that the `redirect_from` section [in the tutorial source code](https://github.com/TuringLang/TuringTutorials/blob/86ab4e5fb7c3b4b105a80e6ade63f40cce7e240d/tutorials/02-logistic-regression/02_logistic-regression.jmd#L4) points to `tutorials/2-logisticregression/` rather than `tutorials/02-logistic-regression`. 

If this is the case, I'd be happy to put in a PR to fix that.

**Comment by devmotion** [comment]
The correct location for the Bayesian logistic regression tutorial is https://turinglang.org/v0.29/tutorials/02-logistic-regression/ You were looking at the old page which is not updated anymore (and, unfortunately, not accessible: https://github.com/TuringLang/Turing.jl/issues/2041).

**Comment by mistermichaelll** [comment]
Ahhh I see - yeah, I went to the link from Google (turing.ml) which explains this.
