### ISSUE TITLE
Converting Bayes NN example to Lux 

### ISSUE THREAD

**Issue by yebai** [TuringLang/TuringTutorials#457]
Let's switch to Lux for the Bayes NN example. The Lux website already provides a conversion that we can adapt: 

https://lux.csail.mit.edu/stable/tutorials/intermediate/2_BayesianNN

cc @avik-pal

**Comment by shravanngoswamii** [comment]
@yebai Do I have to keep things like Plots.jl, NUTS, ReverseDiff and some more things as it is OR replace them to CairoMakie, HMC, Tracker, etc. like in the link you provided just by replicating it!

**Comment by shravanngoswamii** [comment]
ok, I will look into it!
