### ISSUE TITLE
github Title error

### ISSUE THREAD

**Issue by mcprentiss** [TuringLang/TuringTutorials#52]
Should "Educational material (tutorials) for the Turing language. http://turing.ml/tutorials/ "
read as...
"Educational material (tutorials) for the Turing language.  https://turing.ml/dev/tutorials/"?

The  http://turing.ml/tutorials/ link does not exist.

**Comment by cpfiffer** [comment]
Yep. @yebai I can't modify the repository description, could you amend the tutorial link?

**Comment by yebai** [comment]
Sure, should be fixed now.
