### ISSUE TITLE
Project.toml contains MCMCChain, tutorials are using MCMCChains

### ISSUE THREAD

**Issue by SebastianCallh** [TuringLang/TuringTutorials#62]
Running, for instance, the logistic regression tutorial doesn't work out of the box with the current environment since `MCMCChain` (singular) is in Project.toml and `MCMCChains` (plural) in the notebooks. Running `pkg.add("MCMCChains")` makes the `using` statements work and shows `MCMCChains` appearing next to `MCMCChain` in Project.toml.  I assume [this](https://juliapackages.com/packages/mcmcchain) is the correct dependency, but would love some clarification whether it should be `MCMCChains` or `MCMCChains`.

**Comment by cpfiffer** [comment]
It should be MCMCChains, you are correct. Fixed with 1f29c1ee297f00e0a8c379c7d355945d22fa2e00.
