### ISSUE TITLE
Data leakage in Bayesian logistic regression example 

### ISSUE THREAD

**Issue by SebastianCallh** [TuringLang/TuringTutorials#63]
Please see https://github.com/TuringLang/Turing.jl/issues/1235 for details

**Comment by SebastianCallh** [comment]
I have a PR OTW that have fixed the code, but need to get the markdown generation right. I forked before the change in `weave-examples.jl`.

**Comment by cpfiffer** [comment]
Oh, don't worry about that too much. I'll render it to markdown since I'm still trying to get the code to work reliably. If you open a PR with the notebook changes I'll handle it from there.

**Comment by SebastianCallh** [comment]
Alright! Please have a look. Hopefully everything is in order
