### ISSUE TITLE
Specifying target density up to proportionality constant

### ISSUE THREAD

**Issue by luiarthur** [TuringLang/TuringTutorials#66]
In STAN, one can specify a model up to a proportionality constant. For example, the following (uninteresting) STAN code (taken from [here][1]) will generate code that samples from a standard Normal. Note that the target is specified incrementally, in terms of the log density that will be sampled from.

```
parameters {
  real y;
}
model {
  target += -0.5 * y * y;
  // Same as this, which is the full Normal density:
  // target += -0.5 * y * y - log(2*pi) * 0.5 
}
```
Is there something similar in Turing?

[1]: https://mc-stan.org/docs/2_18/reference-manual/increment-log-prob-section.html

**Comment by cpfiffer** [comment]
I'm not sure what you mean. Pretty much all PPLs use the unnormalized density, I thought?

**Comment by luiarthur** [comment]
Thanks for the response!

I know I can (but probably would never) do this in Turing:

```julia

import Random
using Distributions
using Turing

@model myrandnormal(y) = begin
  y ~ Normal(0, 1)
  return y
end

prior_sample = myrandnormal(missing)
prior_sample()  # returns a sample from a standard Normal
```
This will give me samples from a standard Normal distribution. (Same as `randn()`.)

What if I now have probability density function up to a proportionality constant (e.g. because I don't know the proportionality constant)? Can I somehow sample from it? Let's say the density is 
```julia
unnormalized_std_normal_logpdf(y) = -0.5 * y * y
```
which is the unnormalized log density for the standard Normal. One could sample from the implied distribution (given just the log of the unnormalized density) using, say, an appropriate Metropolis-Hastings scheme. So I'm wondering if there's functionality to just provide Turing the above function, and then get samples from it's implied distribution. I feel like the answer is yes, but most likely I haven't found the API in the docs?

**Comment by cpfiffer** [comment]
You would define a custom distribution that is unnormalized, as you might [here](https://turing.ml/dev/docs/using-turing/advanced#how-to-define-a-customized-distribution).

I'm also not really sure what the use case is for this though -- all the distributions in a model are fully parameterized, and so I still don't quite get who is doing this and why.

**Comment by cpfiffer** [comment]
To expand on my answer a little, you would define

```julia
struct WeirdNormal <: Distribution end

Distributions.logpdf(d::WeirdNormal, x::Real) = -0.5 * y * y
Distributions.rand(d::WeirdNormal) = . . . # I'm not sure what the rand would be here
```

**Comment by luiarthur** [comment]
I see. Thanks for the information.

So it seems you would need to implement the sampling algorithm.

For use cases, this is something that happens quite a bit in the Bayesian nonparametric literature, where you can end up with a nonparametric prior, perhaps with a closed-form density. But one of the normalizing constants needs to be enumerate by computing some astronomical combinatorics function. But in many Bayesian inference methods (like Metropolis, Gibbs), these normalizing constants can  be safely ignored as long as they satisfy regularity conditions.

I feel like there is probably no high-level, but some low-level, API to do what I am suggesting (i.e. without creating custom Distributions, but by only specifying an (log) unnormalized pdf). 

I'll look into the source code. Thanks again! I'll close this issue for now and post if I find something.
