### ISSUE TITLE
Gaussian Mixture Models

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/TuringTutorials#7]
[Here's](https://github.com/TuringLang/TuringExamples/blob/master/notebooks/GMM.ipynb) the original example. This one is fairly well commented and just needs a bit more background info thrown in. I may or may not be able to handle this one.

**Comment by trappmartin** [comment]
I think is a rather useful tutorial as many people are familiar with GMMs.

**Comment by trappmartin** [comment]
I’m happy to help on this issue during the next days.

**Comment by cpfiffer** [comment]
Sure, that would be helpful!

**Comment by trappmartin** [comment]
@cpfiffer I think we can close this issue too. What do you think?

**Comment by cpfiffer** [comment]
Yeah, I'd agree. Good work on that one.
