### ISSUE TITLE
Fix unstandardize function.

### ISSUE THREAD

**Issue by GarrettMooney** [TuringLang/TuringTutorials#73]
The `mean` and `std` functions need to be switched in the `unstandardize` function.

This function is found in both the [linear regression](https://github.com/TuringLang/TuringTutorials/blob/master/markdown/5_LinearRegression.md) and the [VI](https://github.com/TuringLang/TuringTutorials/blob/master/markdown/9_VariationalInference.md) tutorials.

I'd be glad to submit a PR but I'll need a bit more guidance as to best practices for this repo.

**Comment by cpfiffer** [comment]
I'm not sure what you mean switched. Do you mean adding the standard deviation? Or do you mean switching the order of operations? If it's the first, I don't think that's right -- you add the mean, then multiply by the standardization. If it's the second, it doesn't matter -- multiplication is commutative.

**Comment by devmotion** [comment]
IMO @GarrettMooney is right, the inverse function to the standardization in `standardize` should be
```julia
function unstandardize(x, orig)
    return x .* std(orig, dims=1) .+ mean(orig, dims=1)
end
```
instead of
```julia
function unstandardize(x, orig)
    return (x .+ mean(orig, dims=1)) .* std(orig, dims=1)
end
```
They are not equivalent since in the current IMO incorrect case the original mean is also scaled with the standard deviation (whereas it should only be a translation afterwards).

**Comment by GarrettMooney** [comment]
I'm realizing that I did not communicate the issue very well but I think David summarized it nicely. 

For an additional intuition check, the current version of the [linear regression notebook](https://github.com/TuringLang/TuringTutorials/blob/master/5_LinearRegression.ipynb) shows that MPG was originally near 20 but the `unstandardize` function transforms predictions for MPG to be closer to 120.

**Comment by cpfiffer** [comment]
Ah, I see. We'd be happy to have a PR to fix this.
