### ISSUE TITLE
UndefVarError: bijector not defined

### ISSUE THREAD

**Issue by caxelrud** [TuringLang/TuringTutorials#92]
Tutorial are key for users to learn.
The Variational Inference notebook has the following error for a long time.

_, sym2range = Variational.bijector(m; sym_to_ranges = Val(true)); #ERROR: UndefVarError: bijector not defined

Also, the following line needs to exclude ".value":
density!(collect(skipmissing(samples_nuts[:s].value)), label = "s (NUTS)", color = :green, linewidth = 2)

Regards,

**Comment by nickto** [comment]
So, do you know the correct way to get sym2range? 

Seems, like Bijectors.bijector has a somewhat similar function signature, but also throws an error.

**Comment by devmotion** [comment]
Was fixed at some point, it seems.
