### ISSUE TITLE
Fix link to https://github.com/TuringLang/TuringTutorials/blob/master/10_diffeq.ipynb

### ISSUE THREAD

**Issue by ChrisRackauckas** [TuringLang/TuringTutorials#96]
This is a somewhat timely manner. Can this link be resurrected for just about a month? Thanks.

**Comment by yebai** [comment]
Fixed by 23f06ba87bb7d6dd77d3467a75d27258194b8738. 

Let's remember to remove this in the future.

**Comment by devmotion** [comment]
@ChrisRackauckas Sorry, just saw your message now. If you want to make the link persistent, you could link to a specific commit. With the switch to markdown tutorials, most links to files in the master branch will become invalid, I assume.

**Comment by ChrisRackauckas** [comment]
It's fine. It's just on the day of a paper release I don't want a broken link since Twitter doesn't allow editing. In a month we can remove this, but for now it's going to get a ton of traffic and "doing it well" is probably better than "doing it right"

**Comment by devmotion** [comment]
I see :slightly_smiling_face: I'm sorry about the inconvenience it caused, I didn't know that you had distributed a link to the repo when fixing the webpage.

**Comment by ChrisRackauckas** [comment]
No worries, it's all good in the end. That's just my impatience to make sure the paper hit the optimal release timing.

**Comment by torfjelde** [comment]
Is it okay if we delete the file now? We're moving to a new format which doesn't use Jupyter notebooks, and so ideally we'd not have to keep the old ones around. We'll also add in redirects, so in the future always link to the website and the underlying notebook can be found from there:)

**Comment by ChrisRackauckas** [comment]
yes, go for it.
